In [3]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print("数组：",arr)
print("形状：",arr.shape)
print("维度：",arr.ndim)

[1 2 3 4 5 6]


In [4]:
!pip install numpy pandas jieba

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.2/19.2 MB 983.5 kB/s  0:00:19 eta 0:00:010:00:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for jieba: filename=jieba-0.42.1-py3-none-any.whl size=19314508 sha256=ca25257f42d145fd580c16516e9a4753c333f7b81c8ca7f851135c535c277b95
  Stored in directory: /Users/lihuijun/Library/Caches/pip/wheels/8d/e9/51/2f0a6a9d051293af20e265d3889beae50efe2de72f8511c801
Successfully built jieba


In [6]:
import pandas as pd
data ={
    "num":[1001,1002,1003,1004,1005],
    "name":["张三","李四","王五","赵六","孙七"],
    "math":[90,78,95,60,88],
    "eng":[85,92,90,70,85],
    "cpgrm":[88,80,94,65,92],
    "gender":["M","F","M","F","M"]
}
df=pd.DataFrame(data)
df.to_csv("score.csv",index=False,encoding="utf-8")
print("文件已创建")



文件已创建
    num name  math  eng  cpgrm gender
0  1001   张三    90   85     88      M
1  1002   李四    78   92     80      F
2  1003   王五    95   90     94      M
3  1004   赵六    60   70     65      F
4  1005   孙七    88   85     92      M
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   num     5 non-null      int64
 1   name    5 non-null      str  
 2   math    5 non-null      int64
 3   eng     5 non-null      int64
 4   cpgrm   5 non-null      int64
 5   gender  5 non-null      str  
dtypes: int64(4), str(2)
memory usage: 372.0 bytes
None
               num       math        eng      cpgrm
count     5.000000   5.000000   5.000000   5.000000
mean   1003.000000  82.200000  84.400000  83.800000
std       1.581139  13.863621   8.619745  11.798305
min    1001.000000  60.000000  70.000000  65.000000
25%    1002.000000  78.000000  85.000000  80.000000
50%    1003.000000  88.000000

In [7]:
import pandas as pd
df=pd.read_csv("score.csv",encoding="utf-8")
print(df.head())
print(df.info())
print(df.describe())

    num name  math  eng  cpgrm gender
0  1001   张三    90   85     88      M
1  1002   李四    78   92     80      F
2  1003   王五    95   90     94      M
3  1004   赵六    60   70     65      F
4  1005   孙七    88   85     92      M
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   num     5 non-null      int64
 1   name    5 non-null      str  
 2   math    5 non-null      int64
 3   eng     5 non-null      int64
 4   cpgrm   5 non-null      int64
 5   gender  5 non-null      str  
dtypes: int64(4), str(2)
memory usage: 372.0 bytes
None
               num       math        eng      cpgrm
count     5.000000   5.000000   5.000000   5.000000
mean   1003.000000  82.200000  84.400000  83.800000
std       1.581139  13.863621   8.619745  11.798305
min    1001.000000  60.000000  70.000000  65.000000
25%    1002.000000  78.000000  85.000000  80.000000
50%    1003.000000  88.000000  85.0

In [8]:
import pandas as pd
df=pd.read_csv("score.csv",encoding="utf-8")
print(df[df["math"]>=90])
print(df[(df["math"]>=85)&(df["eng"]>=90)])


    num name  math  eng  cpgrm gender
0  1001   张三    90   85     88      M
2  1003   王五    95   90     94      M
    num name  math  eng  cpgrm gender
2  1003   王五    95   90     94      M


In [12]:
import pandas as pd
df=pd.read_csv("score.csv",encoding="utf-8")
print(df.groupby("gender")["math"].mean())


gender
F    69.0
M    91.0
Name: math, dtype: float64


In [19]:
import pandas as pd
df=pd.read_csv("score.csv",encoding="utf-8")
df["total"]=df["math"]+df["eng"]+df["cpgrm"]
df["avg"]=df["total"]/3.0
df_sorted=df.sort_values("avg",ascending=False)
print(df_sorted)

    num name  math  eng  cpgrm gender  total        avg
2  1003   王五    95   90     94      M    279  93.000000
4  1005   孙七    88   85     92      M    265  88.333333
0  1001   张三    90   85     88      M    263  87.666667
1  1002   李四    78   92     80      F    250  83.333333
3  1004   赵六    60   70     65      F    195  65.000000


In [20]:
import pandas as pd
df=pd.read_csv("score.csv",encoding="utf-8")
df_sorted.to_csv("score_sorted.csv",index=False,encoding="utf-8")
print("排序结果已保存")

排序结果已保存


In [21]:
import numpy as np
scores=np.array([[90,85,88],[78,92,90],[95,90,94],[60,70,65],[88,85,92]])
print("每人总分:",np.sum(scores,axis=1))
print("每科均分:",np.mean(scores,axis=0))
print("加分后:\n",scores+5)

每人总分: [263 260 279 195 265]
每科均分: [82.2 84.4 85.8]
加分后:
 [[ 95  90  93]
 [ 83  97  95]
 [100  95  99]
 [ 65  75  70]
 [ 93  90  97]]
